-- PostgreSQL Compatible Data Dump (Final)
-- Generated by Laravel ExportPostgresSql

BEGIN;

-- Clean existing data
TRUNCATE TABLE "reviews" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "order_items" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "orders" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "product_categories" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "product_variants" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "product_images" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "products" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "customers" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "testimonials" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "themes" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "banners" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "settings" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "categories" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "role_has_permissions" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "model_has_roles" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "roles" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "permissions" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "users" RESTART IDENTITY CASCADE;

-- Data for users
INSERT INTO "users" ("id", "name", "email", "email_verified_at", "password", "phone", "avatar", "is_active", "remember_token", "created_at", "updated_at") VALUES (1, 'Super Admin', 'admin@ratannam.com', '2026-01-25 05:40:24', '$2y$12$FqwDh5jQxsBrb.MynBdkPOVcvhae8r0We5FgWgqBfyehNkl0tYwGy', NULL, NULL, TRUE, NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "users" ("id", "name", "email", "email_verified_at", "password", "phone", "avatar", "is_active", "remember_token", "created_at", "updated_at") VALUES (2, 'Store Manager', 'manager@ratannam.com', '2026-01-25 05:40:25', '$2y$12$L58ywmFNkAhQajCGg3Xg4uui2z5Pf64qAmYX6.gx7IHqonuKNA.kW', NULL, NULL, TRUE, NULL, '2026-01-25 05:40:25', '2026-01-25 05:40:25');
INSERT INTO "users" ("id", "name", "email", "email_verified_at", "password", "phone", "avatar", "is_active", "remember_token", "created_at", "updated_at") VALUES (3, 'John Doe', 'customer@ratannam.com', '2026-01-25 05:40:25', '$2y$12$ulPAREj9wT2gRIY.f1GEZefrRyeUqAZsDZXlPofhXqmSXFZac3j3O', NULL, NULL, TRUE, NULL, '2026-01-25 05:40:25', '2026-01-25 05:40:25');

-- Data for permissions
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (1, 'product.view', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (2, 'product.create', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (3, 'product.edit', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (4, 'product.delete', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (5, 'category.view', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (6, 'category.create', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (7, 'category.edit', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (8, 'category.delete', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (9, 'order.view', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (10, 'order.create', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (11, 'order.edit', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (12, 'order.delete', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (13, 'customer.view', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (14, 'customer.create', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (15, 'customer.edit', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (16, 'customer.delete', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (17, 'review.view', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (18, 'review.create', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (19, 'review.edit', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (20, 'review.delete', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (21, 'banner.view', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (22, 'banner.create', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (23, 'banner.edit', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (24, 'banner.delete', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (25, 'user.view', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (26, 'user.create', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (27, 'user.edit', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (28, 'user.delete', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (29, 'role.view', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (30, 'role.create', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (31, 'role.edit', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (32, 'role.delete', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (33, 'settings.view', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (34, 'settings.create', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (35, 'settings.edit', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (36, 'settings.delete', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (37, 'dashboard.view', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "permissions" ("id", "name", "guard_name", "group_name", "created_at", "updated_at") VALUES (38, 'media.upload', 'web', NULL, '2026-01-25 05:40:24', '2026-01-25 05:40:24');

-- Data for roles
INSERT INTO "roles" ("id", "name", "guard_name", "created_at", "updated_at") VALUES (1, 'Super Admin', 'web', '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "roles" ("id", "name", "guard_name", "created_at", "updated_at") VALUES (2, 'Manager', 'web', '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "roles" ("id", "name", "guard_name", "created_at", "updated_at") VALUES (3, 'Admin', 'web', '2026-01-25 05:40:24', '2026-01-25 05:40:24');
INSERT INTO "roles" ("id", "name", "guard_name", "created_at", "updated_at") VALUES (4, 'Customer', 'web', '2026-01-25 05:40:24', '2026-01-25 05:40:24');

-- Data for model_has_roles
INSERT INTO "model_has_roles" ("role_id", "model_type", "model_id") VALUES (1, 'App\Models\User', 1);
INSERT INTO "model_has_roles" ("role_id", "model_type", "model_id") VALUES (2, 'App\Models\User', 2);
INSERT INTO "model_has_roles" ("role_id", "model_type", "model_id") VALUES (4, 'App\Models\User', 3);

-- Data for role_has_permissions
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (1, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (1, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (1, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (2, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (2, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (2, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (3, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (3, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (3, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (4, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (4, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (4, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (5, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (5, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (5, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (6, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (6, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (6, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (7, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (7, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (7, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (8, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (8, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (8, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (9, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (9, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (9, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (10, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (10, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (10, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (11, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (11, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (11, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (12, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (12, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (12, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (13, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (13, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (14, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (14, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (15, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (15, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (16, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (16, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (17, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (17, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (17, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (18, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (18, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (18, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (19, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (19, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (19, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (20, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (20, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (20, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (21, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (21, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (21, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (22, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (22, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (22, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (23, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (23, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (23, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (24, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (24, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (24, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (25, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (25, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (26, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (26, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (27, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (27, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (28, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (28, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (29, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (30, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (31, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (32, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (33, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (33, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (34, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (34, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (35, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (35, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (36, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (37, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (37, 2);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (37, 3);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (38, 1);
INSERT INTO "role_has_permissions" ("permission_id", "role_id") VALUES (38, 3);

-- Data for categories
INSERT INTO "categories" ("id", "name", "description", "slug", "icon", "parent_id", "image", "position", "is_active", "meta_title", "meta_description", "meta_keywords", "deleted_at", "created_at", "updated_at") VALUES (1, 'Gold Jewellery', 'Exquisite 22k and 18k gold jewellery collections.', 'gold-jewellery', 'bi bi-gem', NULL, NULL, 0, TRUE, 'Gold Jewellery - Ratannam Gold', 'Exquisite 22k and 18k gold jewellery collections.', NULL, NULL, '2026-01-25 05:40:25', '2026-01-25 05:40:25');
INSERT INTO "categories" ("id", "name", "description", "slug", "icon", "parent_id", "image", "position", "is_active", "meta_title", "meta_description", "meta_keywords", "deleted_at", "created_at", "updated_at") VALUES (2, 'Silver Jewellery', 'Premium sterling silver accessories.', 'silver-jewellery', 'bi bi-stars', NULL, NULL, 1, TRUE, 'Silver Jewellery - Ratannam Gold', 'Premium sterling silver accessories.', NULL, NULL, '2026-01-25 05:40:25', '2026-01-25 05:40:25');
INSERT INTO "categories" ("id", "name", "description", "slug", "icon", "parent_id", "image", "position", "is_active", "meta_title", "meta_description", "meta_keywords", "deleted_at", "created_at", "updated_at") VALUES (3, 'Bridal Jewellery', 'Complete bridal sets for your special day.', 'bridal-jewellery', 'bi bi-heart-fill', NULL, NULL, 2, TRUE, 'Bridal Jewellery - Ratannam Gold', 'Complete bridal sets for your special day.', NULL, NULL, '2026-01-25 05:40:25', '2026-01-25 05:40:25');
INSERT INTO "categories" ("id", "name", "description", "slug", "icon", "parent_id", "image", "position", "is_active", "meta_title", "meta_description", "meta_keywords", "deleted_at", "created_at", "updated_at") VALUES (4, 'Daily Wear Jewellery', 'Lightweight and stylish jewellery for everyday elegance.', 'daily-wear-jewellery', 'bi bi-sun', NULL, NULL, 3, TRUE, 'Daily Wear Jewellery - Ratannam Gold', 'Lightweight and stylish jewellery for everyday elegance.', NULL, NULL, '2026-01-25 05:40:25', '2026-01-25 05:40:25');
INSERT INTO "categories" ("id", "name", "description", "slug", "icon", "parent_id", "image", "position", "is_active", "meta_title", "meta_description", "meta_keywords", "deleted_at", "created_at", "updated_at") VALUES (5, 'Men & Kids', 'Exclusive collections for men and children.', 'men-kids', 'bi bi-people', NULL, NULL, 4, TRUE, 'Men & Kids - Ratannam Gold', 'Exclusive collections for men and children.', NULL, NULL, '2026-01-25 05:40:25', '2026-01-25 05:40:25');
INSERT INTO "categories" ("id", "name", "description", "slug", "icon", "parent_id", "image", "position", "is_active", "meta_title", "meta_description", "meta_keywords", "deleted_at", "created_at", "updated_at") VALUES (6, 'Coins & Gifts', 'Gold/Silver coins and gifting articles.', 'coins-gifts', 'bi bi-coin', NULL, NULL, 5, TRUE, 'Coins & Gifts - Ratannam Gold', 'Gold/Silver coins and gifting articles.', NULL, NULL, '2026-01-25 05:40:25', '2026-01-25 05:40:25');
INSERT INTO "categories" ("id", "name", "description", "slug", "icon", "parent_id", "image", "position", "is_active", "meta_title", "meta_description", "meta_keywords", "deleted_at", "created_at", "updated_at") VALUES (7, 'Gold Rings', NULL, 'gold-rings', NULL, NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL, '2026-01-25 05:40:25', '2026-01-25 05:40:25');

-- Data for settings
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (1, 'site_name', 'Ratannam Gold', 'general', 'string', NULL, NULL);
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (2, 'site_logo', '/images/logo.png', 'general', 'string', NULL, NULL);
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (3, 'contact_email', 'info@ratannam.com', 'general', 'string', NULL, NULL);
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (4, 'currency_symbol', '₹', 'finance', 'string', NULL, NULL);
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (5, 'active_theme', 'default', 'theme', 'string', NULL, NULL);
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (6, 'rate_gold_24k', 156000, 'rates', 'number', '2026-01-25 05:49:58', '2026-01-25 05:49:58');
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (7, 'rate_gold_22k', 135000, 'rates', 'number', '2026-01-25 05:49:58', '2026-01-25 05:49:58');
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (8, 'rate_silver', 295000, 'rates', 'number', '2026-01-25 05:49:58', '2026-01-25 05:49:58');
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (9, 'show_gold_prices', 0, 'rates', 'boolean', '2026-01-25 05:49:58', '2026-01-25 05:50:16');
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (10, 'show_silver_prices', 0, 'rates', 'boolean', '2026-01-25 05:49:58', '2026-01-25 05:50:16');
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (11, 'app_name', 'Ratannam Gold', 'global', 'string', '2026-01-25 05:56:30', '2026-01-25 05:56:30');
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (12, 'hide_prices', 0, 'general', 'boolean', '2026-01-25 05:56:30', '2026-01-25 07:33:54');
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (13, 'store_phone', NULL, 'general', 'string', '2026-01-25 07:33:54', '2026-01-25 07:33:54');
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (14, 'contact_whatsapp', NULL, 'general', 'string', '2026-01-25 07:33:54', '2026-01-25 07:33:54');
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (15, 'map_coordinates', '25.773949, 73.339001', 'general', 'string', '2026-01-25 07:33:54', '2026-01-25 07:33:54');
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (16, 'contact_address', NULL, 'general', 'string', '2026-01-25 07:33:54', '2026-01-25 07:33:54');
INSERT INTO "settings" ("id", "key", "value", "group", "type", "created_at", "updated_at") VALUES (17, 'google_map_embed', NULL, 'general', 'string', '2026-01-25 07:33:54', '2026-01-25 07:33:54');

-- Data for banners
INSERT INTO "banners" ("id", "title", "subtitle", "text_alignment", "content_position", "image_path", "mobile_image_path", "content_image_path", "button_text", "button_link", "sort_order", "is_active", "show_content", "show_content_image", "overlay_opacity", "animate_image", "created_at", "updated_at") VALUES (1, 'New Collection', NULL, 'center', 'center', '/images/banner1.jpg', NULL, NULL, NULL, NULL, 0, FALSE, TRUE, TRUE, 0.6, TRUE, '2026-01-25 05:40:25', '2026-01-25 05:54:27');

-- Data for products
INSERT INTO "products" ("id", "name", "slug", "short_description", "description", "product_type", "brand_id", "price", "sale_price", "sale_start", "sale_end", "tax_class", "sku", "stock_quantity", "manage_stock", "stock_status", "material", "purity", "weight", "is_active", "is_trending", "show_on_homepage", "thumbnail", "gallery", "meta_title", "meta_description", "meta_keywords", "deleted_at", "created_at", "updated_at") VALUES (1, 'Classic Gold Band', 'classic-gold-band', NULL, 'A timeless classic gold band.', 'simple', NULL, 25000.00, 23750.00, NULL, NULL, NULL, 'YXYTMJ24', 10, TRUE, 'instock', 'Gold', NULL, NULL, TRUE, TRUE, FALSE, 'products/VYtLNGYIJY3TdOzwswIRPL7zDdsSrcmlyav901rO.png', NULL, NULL, NULL, NULL, NULL, '2026-01-25 05:40:25', '2026-01-25 05:44:26');

-- Data for product_images
INSERT INTO "product_images" ("id", "product_id", "image_path", "is_primary", "created_at", "updated_at") VALUES (1, 1, 'products/VYtLNGYIJY3TdOzwswIRPL7zDdsSrcmlyav901rO.png', TRUE, '2026-01-25 05:43:58', '2026-01-25 05:43:58');

-- Data for product_categories
INSERT INTO "product_categories" ("id", "product_id", "category_id", "created_at", "updated_at") VALUES (1, 1, 7, '2026-01-25 05:40:25', '2026-01-25 05:40:25');

COMMIT;
